.cargo_build_template: &cargo_build
  stage: build
  script:
    - cargo build --release --workspace --jobs 1

.cargo_deploy_template: &cargo_publish
  stage: publish
  before_script:
    - cargo login $CARGO_REGISTRY_TOKEN
    - cargo fmt --all
  script:
    - cargo publish -p conduit-sdk -v

.cargo_test_template: &cargo_test
  stage: test
  script:
    - cargo test --all-features --release --jobs 1

stages:
  - build
  - publish
  - test

variables:
  CARGO_REGISTRY_TOKEN: $CARGO_REGISTRY_TOKEN
  CONTAINER_NAME: "conduit"
  DOCKER_HOST: "ssh://deploy@$DOCKER_HOST_IP"
  DOCKERHUB_TOKEN: $DOCKERHUB_TOKEN
  DOCKERHUB_USERNAME: $DOCKERHUB_USERNAME

docker:deploy:
  image: docker:dind
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
  stage: publish
  before_script:
    - docker login --password $DOCKERHUB_TOKEN --username $DOCKERHUB_USERNAME https://registry.hub.docker.com
  script:
    - docker build --tag $DOCKERHUB_USERNAME/$CONTAINER_NAME:latest
    - docker publish $DOCKERHUB_USERNAME/$CONTAINER_NAME:$CI_COMMIT_TAG
    - docker publish $DOCKERHUB_USERNAME/$CONTAINER_NAME:latest
  after_script:
    - docker logout

stable:rust:
  image: rustdocker/rust:stable
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
  <<: *cargo_build
  <<: *cargo_test
  <<: *cargo_publish

nightly:rust:
  allow_failure: true
  image: rustdocker/rust:nightly
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
  <<: *cargo_build
  <<: *cargo_test
  <<: *cargo_publish


